### ISSUE TITLE
Change randomize function

### ISSUE THREAD

**Issue by SJosefsson** [SJosefsson/passwordgenerator#1]
As random is not quite... random, it would be good to research and use another randomize function

**Comment by reetMzkd** [comment]
Maybe this is an option
![Captura de pantalla (4)](https://user-images.githubusercontent.com/58600817/87849752-5f4d6980-c8eb-11ea-87c6-66f4e179de65.png)

**Comment by SJosefsson** [comment]
I really like this solution, thank you!

**Comment by SJosefsson** [comment]
Randomize function has been changed to use secrets library instead of random liabrary.
